### ISSUE TITLE
getControlEvents.xql need app.xql from proofMEIdata

### ISSUE THREAD

**Issue by bwbohl** [Freischuetz-Digital/pmdCE-new#1]

**Comment by elena1113** [comment]
i added yesterday package "module" from proffMEIdata: https://github.com/Freischuetz-Digital/pmdCE-new/commit/41fa5b4a88f748d2612b40f89649255757852659.
It contains app.xql....

**Comment by bwbohl** [comment]
ok, I'll try rebuilding locally, thx!
